### ISSUE TITLE
please remember keeping versions updated

### ISSUE THREAD

**Issue by IzzySoft** [Smooth-E/monet-color-previewer#1]
Currently there are two releases tagged, v1.0 and v1.1. The APKs on both identify as

    package: name='com.smoothie.monetcolors' versionCode='1' versionName='1.0'

because [versions were not updated](https://github.com/Smooth-E/monet-color-previewer/blob/main/app/build.gradle#L12) – so they are hard to keep apart:

* because `versionName` wasn't changed, folks cannot really see which version they have installed
* because `versionCode` was not updated, Android will not recognize v1.1 as update to an installed v1.0

Can you please keep track of that with future releases? Thanks in advance!

**Comment by Smooth-E** [comment]
Thanks for pointing out. I will ensure that for future releases version number and the name are properly modified. Not sure how I missed this step.

Is it appropriate to edit this information for Release v1.1 and re-upload the modified APK or should I keep this change for future releases? 

As far as I know, when you are editing the release, GitHub makes a new snapshot of the source code tree and attaches it as a *.tar*. If this is true, editing the release now will result in a confusion since I recently pushed some changes that I made long time ago along with fixing typos in README and those changes should not be included in a snapshot along with Release v1.1

What are your thoughts on this?

**Comment by IzzySoft** [comment]
> Is it appropriate to edit this information for Release v1.1 and re-upload the modified APK or should I keep this change for future releases?

That's your decision – and might depend on how you want to approach that. If your app is not yet listed on any store (which I assume, as otherwise you'd have noticed this problem earlier), there's no real problem with editing a release. You could simply replace the attached APK – but then, that would not correspond to the commit the tag/release is associated with (not a big deal in this specific case, but still might cause some confusion). Easiest would probably be to make a "maintenance release" (e.g. v1.1.1) at the proper commit, so all is "in sync".

> As far as I know, when you are editing the release, GitHub makes a new snapshot of the source code tree and attaches it

Not if you only adjust the release comment or add/remove attachments (would make no sense, as they'd need to build the very same tarball from the very same commit they did before).

But anyhow: I'd suggest making a "maintenance release" at a commit where you've fixed the versioning. That could happen in two ways:

* if you feel the current HEAD fine for that: increase VC to e.g. `3`, set VN to e.g. `1.1.1`, commit, tag, release.
* if you feel it in a state not fit for release: create a new branch off the last commit you feel fit, adjust VC/VN there, commit and create a tag/release on the commit in that branch. Then either merge that branch back to `main`, or simply repeat the versioning adjustments on `main` at its HEAD.

If you go with a branch the remaining question is just if you want to retain that branch "forever" – because if you delete it, the tag would point to NIL :wink:

Just let me know when a release with a properly versioned APK is up please, so I can include your app with [my repo](https://apt.izzysoft.de/fdroid) :smiley:

**Comment by Smooth-E** [comment]
The new release is now ready! In addition to fixing the versioning issue I decided to also upgrade dependencies and fix some visual issues ([temporarily](https://github.com/Smooth-E/monet-color-previewer/releases/tag/v1.2)). I am glad to be invited to your app repository!

You are free to test the release if you want and tell me about any issues other than these listed under *Known Issues*.

I also have a small question. I know that when you are publishing for F-Droid, you should add the fastlane metadata thing. Do I have to do anything like that before you will be able to publish the app in your repository?

I also released [this](https://github.com/Smooth-E/wireless-adb-switch) useful app somewhat recently. Maybe you will be interested in adding it to your repository as well.

**Comment by IzzySoft** [comment]
> The new release is now ready!

Integrating it with my repo at this very moment, thanks! Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for integration with e.g. your Readme, to link to [where it will show up](https://apt.izzysoft.de/packages/com.smoothie.monetcolors/) with the next sync!

> I know that when you are publishing for F-Droid, you should add the fastlane metadata thing.

Set up now in my repo – so if you need it, let me know and I'll send you a PR with a "starter package" :smiley:

> Maybe you will be interested in adding it to your repository as well.

Taking a look now, thanks!

**Comment by Smooth-E** [comment]
> Set up now in my repo – so if you need it, let me know and I'll send you a PR with a "starter package"

I don't really understand what you meant to say here 🥲 
Yeah, sure, make that pull request. I guess, filling out the metadata myself will give me more control on how the app looks in the store.

However, judging from your message, you have already filled all of the data yourself. So, I will only need to update the metadata when I make a new release or something, right?

Also, how are changelogs handled in such application repositories? Are they just scraped from GitHub (and other code hosting services) releases or should they be provided in the metadata?

And I also have an additional question to ask, while we are at it. I know that such repositories as yours are mainly focused on providing open source apps. People in F-Droid's Matrix chat said I can not publish games made with proprietary engine, such as Unity, to F-Droid (given that the game itself is open). How is that in your repository?

**Comment by IzzySoft** [comment]
> I don't really understand what you meant to say here

OK, phrasing it differently: your apps are both live now in my repo – and when you want to bring them to F-Droid.org and thus need Fastlane, give me a ping and I provide the necessary files via a pull request to your repo here :wink:

> Yeah, sure, make that pull request. I guess, filling out the metadata myself will give me more control on how the app looks in the store.

Definitely! That's the idea. You know best when things need to be changed there :smile:

> However, judging from your message, you have already filled all of the data yourself. So, I will only need to update the metadata when I make a new release or something, right?

Whenever you feel something needs to be changed – and yes, updates to that would be picked up along with the release then.

> Also, how are changelogs handled in such application repositories?

By your providing them with the Fastlane structures. Be welcome to my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) :smiley:

As for games: I usually do not include games at all with my repo. But other than F-Droid, I have no means to check your build process as I only pick the APKs. So all I can check are the resulting APK files and what they contain – not how stuff got in there.

**Comment by Smooth-E** [comment]
So cool! Thank you! Anyways, as everything seems clear now, I am closing the issue.

**Comment by IzzySoft** [comment]
… and continue "over there" :see_no_evil:
