### ISSUE TITLE
Fastlane issues

### ISSUE THREAD

**Issue by IzzySoft** [Smooth-E/monet-color-previewer#3]
Please note the limits of files in your fastlane structure: per-release changelogs can only have max 500 chars.

    metadata/com.smoothie.monetcolors/en-US/changelogs/3.txt has 602 chars

So the last 102 chars are truncated. I've adjusted `3.txt` manually for now so no information is lost – but please take care with future releases to not go beyond the limits. Thanks!

**Comment by Smooth-E** [comment]
Fixed. Thanks for raising the issue.

While browsing some of your Fastlane-related documentation on GitLab I read that a developer have to notify you when they update their Fastlane data. What is the best way to do this? For example, if I will create a pull request which adds Fastlane screenshots and in its initial comment I will @IzzySoft you, will you be notified (through GitHub notifications / email)?

**Comment by IzzySoft** [comment]
Thanks!

> a developer have to notify you when they update their Fastlane data

not fully correct: only if you added "element types" previously not present (e.g. if you had no featureGraphic before but now you have). If you e.g. had screenshots before and just updated them or added some more, that will be handled automatically. Reason behind that is that I prefer to check what you added to see what the best way for integration is, so I can optimize. Example: you use a `featureGraphic.png` that will be 100+ kB no matter what, but if converted to JPG it would be e.g. 30 kB without much visual difference, I'd set it up to be converted (I always have low-end devices and "bad connections" in mind, for the more unfortunate people).

So in case you added a new "element type": a ping from here is fine, I'll get a notification then and will act ASAP.
